import { test, expect } from '@playwright/test';

test('Basic Flow: Add to card check out @flow1', async ({ page }) => {
  await page.goto('https://tester11222.github.io/Dummy-Website/');
  await page.getByRole('link', { name: 'Shop', exact: true }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).first().click();
  await page.getByText('✓Added to cart!').click();
  await page.getByRole('button', { name: '🛒' }).click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('T');
  await page.getByRole('textbox', { name: 'you@example.com' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('Testing');
  await page.getByRole('textbox', { name: '+1 (555) 000-' }).click();
  await page.getByRole('textbox', { name: '+1 (555) 000-' }).fill('03333569854');
  await page.getByRole('textbox', { name: 'James' }).click();
  await page.getByRole('textbox', { name: 'James' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'James' }).fill('T');
  await page.getByRole('textbox', { name: 'James' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'James' }).fill('Test');
  await page.getByRole('textbox', { name: 'Morrison' }).click();
  await page.getByRole('textbox', { name: 'Morrison' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Morrison' }).fill('U');
  await page.getByRole('textbox', { name: 'Morrison' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Morrison' }).fill('User');
  await page.getByRole('textbox', { name: 'you@example.com' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('Testing@gmail.com');
  await page.getByRole('textbox', { name: 'Main Street, Apt 4B' }).click();
  await page.getByRole('textbox', { name: 'Main Street, Apt 4B' }).fill('123 ');
  await page.getByRole('textbox', { name: 'New York' }).click();
  await page.getByRole('textbox', { name: 'New York' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'New York' }).fill('N');
  await page.getByRole('textbox', { name: 'New York' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'New York' }).fill('New ');
  await page.getByRole('textbox', { name: 'New York' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'New York' }).fill('New Y');
  await page.getByRole('textbox', { name: 'New York' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'New York' }).fill('New York');
  await page.getByRole('textbox', { name: 'NY' }).click();
  await page.getByRole('textbox', { name: 'NY' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'NY' }).fill('NY');
  await page.getByRole('textbox', { name: '10001' }).click();
  await page.getByRole('textbox', { name: '10001' }).fill('1001');
  await page.getByRole('button', { name: 'Continue to Payment →' }).click();
  await page.getByRole('button', { name: 'Review Order →' }).click();
  await page.getByRole('textbox', { name: 'James Morrison' }).click();
  await page.getByRole('textbox', { name: 'James Morrison' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'James Morrison' }).fill('t');
  await page.getByRole('textbox', { name: 'James Morrison' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'James Morrison' }).fill('T');
  await page.getByRole('textbox', { name: 'James Morrison' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'James Morrison' }).fill('Test ');
  await page.getByRole('textbox', { name: 'James Morrison' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'James Morrison' }).fill('Test C');
  await page.getByRole('textbox', { name: 'James Morrison' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'James Morrison' }).fill('Test Card');
  await page.getByRole('textbox', { name: '5678 9012 3456' }).click();
  await page.getByRole('textbox', { name: '5678 9012 3456' }).fill('4242 4242 4242 4242');
  await page.getByText('Expiry Date Invalid expiry').click();
  await page.getByRole('textbox', { name: 'MM / YY' }).fill('12 / 36');
  await page.getByRole('textbox', { name: '123', exact: true }).click();
  await page.getByRole('textbox', { name: '123', exact: true }).fill('123');
  await page.getByRole('button', { name: 'Review Order →' }).click();
  await page.getByRole('button', { name: '🔒 Place Order' }).click();
  await page.getByRole('checkbox', { name: 'I agree to the Terms of' }).check();
  await page.getByRole('button', { name: '🔒 Place Order' }).click();
  await page.getByRole('link', { name: 'Back to Home' }).click();
  await page.getByRole('listitem').filter({ hasText: 'About' }).click();
  await page.getByText('Home Shop New Arrivals Sale').click();
  await page.getByRole('navigation').getByRole('link', { name: 'Sale' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'New Arrivals' }).click();
  await page.getByRole('link', { name: 'Shop' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Home' }).click();
});